<template>
  <v-container>
    <span class="display-2"> Frequently asked questions <br /><br /> </span>
    <v-expansion-panels>
      <v-expansion-panel v-for="qa in qas" :key="qa.q">
        <v-expansion-panel-header>
          <span class="title">{{ qa.q }}</span>
        </v-expansion-panel-header>
        <v-expansion-panel-content
          ><span v-html="qa.a"
        /></v-expansion-panel-content>
      </v-expansion-panel>
    </v-expansion-panels>
    <br />
    <br />
    <p v-html="extrainfo" class="px-5 title" />
  </v-container>
</template>

<script>
export default {
  data() {
    return {
      qas: [
        {
          q: 'How do you avoid spam and ensure reliable reviews and ratings?',
          a: ` 
            Mangrove applies a variety of measures to ensure a high reliability of ratings and usefulnes of the database:
            <ul>
              <li><b>Users can mark reviews</b> as ‘useful’, and they can ‘confirm the experience’ expressed in a review. This information is used by the aggregation algorithm to give high quality reviews a higher weight in the aggregated rating, and display them higher up in the list.</li>
              <li>Users can <b>‘flag as inappropriate’</b> if a review is violating the Terms of Use, so that abusive content and harassment do not get spread.</li>
              <li>Reviewers are assigned a <b>'reliability score'</b> by the aggregation algorithm, reflecting their track record and quality.</li>
              <li><b>Businesses can reply</b> to their customer's reviews, thereby allowing a more balanced view, especially when conflicts occurred.</li>
              <li><b>Businesses can invite their customers</b> to leave reviews, allowing to mark those reviews as 'verified purchases'.</li>
              <li>The Mangrove <b>aggregation algorithm uses probabilistic models</b> to identify fraudulent reviews and devalue them, as well as flag them as probably fraudulent to the viewer.</li>
              <li>If reviews clearly violate the Terms of Use (abusive content and harassment), they are not deleted but moved to a different database where Mangrove stores them in case of a dispute. The original review entry will still be visible, but instead of the abusive content a note is displayed why the content was removed.</li>
            </ul>
            We believe---and want to prove---that good algorithms, and a community with a strong sense of citizenship can achieve a reliable outcome without the control of a centralized authority. 
          `
        },
        {
          q: 'How does Mangrove protect the privacy of users?',
          a: `
            <ul>
              <li><b>No registration</b> or login process requiring personal data.</li>
              <li><b>No tracking</b>, no cookies, no gathering of user data behind the scenes, and no advertisement.</li>
              <li>We use <b>public key cryptography</b> to create an identity for users within Mangrove so that we can establish reputation within the system.</li>
              <li>A reviewer can have several identities in Mangrove by creating as many public keys as they wish. They are all linked to one root secret key (=private key) which only the reviewer holds. Neither Mangrove nor anyone else can connect the public keys to the same person.</li>
              <li>The cryptographic key pair is generated by the user’s browser, and it is <b>stored locally on the device</b> within the browser’s IndexedDB (we strongly recommend copying and storing your private key in a cross-device password manager).</li>
            </ul>
          `
        },
        {
          q:
            'What’s a cryptographic key pair and why do I need to store my private key?',
          a: `
            When you write a review within Mangrove, your browser generates a cryptographic key pair, consisting of a public key and a private key, and it saves both in its storage (IndexedDB) on your device.
            <ul>
              <li><b>Public key</b>: Your review will be stored in the Mangrove open dataset together with the public key. So it serves as an identifier for you, and removes the need for a registration or login process. This identifier allows us to assign a reputation to you: the more reviews you write using the same public key, and the more upvotes you get, the more weight your reviews receive. You can always generate new public keys, e.g., if you want to review something that you do not wish to link to your other reviews. All your public keys are connected to the same private key and can be accessed through it. Each time you write a review you can choose the public key you’d like to use, or generate a new one.</li>
              <li><b>Private key</b>: It serves as a secret password that allows you to access your public keys. Only if you hold the private key, you can access your public keys from any device, and re-import it in case your browser’s storage gets cleared for some reason.</li>
            </ul>
            Please note that the key pairs are generated and stored locally on your device. This means that Mangrove is not able to see or to store your private key. In case you lose the private key, Mangrove does not have any possibility to recover it. <b>We recommend to save the private key in a password manager</b> (e.g., open source and privacy-preserving Bitwarden) that you have on multiple devices. So you can easily import the private key if you use different devices to write reviews.
          `
        },
        {
          q: 'Who is behind the Mangrove initiative?',
          a: `
            Mangrove is an open source and non-profit community project started by PlantingSpace, a limited liability company incorporated in Zug, Switzerland. Mangrove’s financial resources are managed 100% transparently via Open Collective, and PlantingSpace LLC has the role of a Fiscal Host, meaning that it is the legal entity holding the money and responsible for admin/taxes forms for the Collective.
          `
        },
        {
          q: 'How is Mangrove funded?',
          a: `
            Mangrove is funded by donations and sponsors. All financial resources are managed 100% transparently via Open Collective.<br/><br/>
            We believe that creating and maintaining an open data commons is not compatible with profit orientation. We believe it can nevertheless 
            be done if we work in a very efficient and cost-effective manner, so that the commons can be maintained purely by donations and sponsorship 
            from people who believe in its value. However, we hope that the open dataset will serve as a ground for many revenue-generating services 
            and products built on top of it, and that these services and products will contribute back to the initiative.<br/><br/>
            If you run a business and are using the Mangrove open dataset in a revenue-generating service, it makes business sense to 
            sponsor Mangrove: it ensures the project that your service relies on stays healthy and actively maintained. It can also 
            help your exposure in the Open Data community.<br/><br/>
            If you are an individual user and have enjoyed sharing and gaining insights through Mangrove reviews, consider donating as a 
            sign of appreciation - like offering the Mangrove developers a coffee once in a while :)  
          `
        },
        {
          q: 'What databases does Mangrove use?',
          a: `
            <ul>
              <li><b>Places on the map: OpenStreetMap</b>. OpenStreetMap is built by a community of mappers that contribute and maintain data about roads, trails, cafés, railway stations, and much more, all over the world. OpenStreetMap's community is diverse, passionate, and growing every day. Contributors include enthusiast mappers, GIS professionals, engineers running the OSM servers, humanitarians mapping disaster-affected areas, and many more.</li>
              <li><b>Companies: GLEIF’s Legal Entity Identifier (LEI):</b> GLEIF is a supra-national not-for-profit organization established by the Financial Stability Board in June 2014 tasked to support the implementation and use of the Legal Entity Identifier (LEI). The LEI is a 20-character, alpha-numeric code based on the ISO 17442 standard developed by the International Organization for Standardization (ISO). It connects to key reference information that enables clear and unique identification of legal entities participating in financial transactions. Each LEI contains information about an entity’s ownership structure and thus answers the questions of ‘who is who’ and ‘who owns whom’.</li>
              <li><b>Books: Internet Archive’s Open Library.</b> Open Library is an open, editable library catalog, building towards a web page for every book ever published.</li>
            </ul
            Read more about the databases and tools used by Mangrove, as well as the principles guiding the design choices, in the Mangrove Review Standard in our GitLab repository.
          `
        }
      ],
      extrainfo: `Not found what you were looking for? Contact us at hello(at)mangrove(dot)reviews, or talk to us in our <a href="https://matrix.to/#/!NWvCdVEAXYJRnXTudO:matrix.org?via=matrix.org">Riot chat on Matrix</a>.`
    }
  }
}
</script>
