# Custom nav
nav:
  title: "MANGROVE blog"

favicon: ""

# Custom background
background:
  color: "#eff0f6"
  image: ""

# Social media
social:
  Mastodon: https://mas.to/@mangroveReviews
  Twitter: https://twitter.com/mangroveReviews

# Custom footer
mail: mangrove@planting.space
copyright: A PlantingSpace Project — CC-BY-4.0

# Custom menu. You can specific the path or the card style (only useful for category page).
# Two kinds of card style: 'project-card', 'article-card',
# Never mind the name.
menu:
  # Project:
  #   path: /categories/Projects
  #   card: project-card
  # Stuffs:
  #   path: /tags/Stuffs
  #   card: article-card
  Home: /
  Archive: /archives
  Mangrove: https://mangrove.reviews

# Specific default categories or tags of home page.
# Post which belongs to `category` or `tag` and don't belongs to `except_category` or `except_tag` will be filtered.
home:
  # set card style of home page
  # category: Projects
  # tag: 算法
  # except_category: 树
  # except_tag:
  #   - 总结
  #   - css

card_style:
  home: project-card
  archive: article-card
  tag: article-card
  category: article-card

# category page
category_generator:
  category_per_page: 3
  post_per_category: 3

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false