[package]
name = "reviewer"
version = "0.1.0"
authors = ["keorn <git@i.keorn.org>"]
edition = "2018"
default-run = "main"

[dependencies]
log = "0.4"
rand = "0.6"
base64-url = "1.1"
url = "2.1.0"
isbn = "0.2.0"
ring = "0.16.9"
biscuit = { git = "https://github.com/plantingspace/biscuit" }
diesel = { version = "1.0.0", features = ["postgres", "serde_json"] }
xmltree = "0.8.0"
reqwest = "0.9.24"
serde = { version = "1.0.90", features = ["derive"] }
serde_cbor = "0.10.2"
serde_json = "1.0"
csv = "1.1.1"
schemars = "0.6.1"
okapi = "0.3.0"
dotenv = "0.9.0"
rocket = { version = "0.4", default-features = false }
rocket_cors = "0.5.0"
rocket_lamb = "0.6.0"
rocket_okapi = "0.3.1"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["diesel_postgres_pool", "diesel_sqlite_pool", "json"]