version: '2.0'
services:
  # builds lambda package
  build:
    image: quay.io/open-reviews/lambda-rust
    volumes:
    - .:/code
    - ~/.cargo/registry:/root/.cargo/registry
    environment:
    - BIN=lambda
